version: "3.8"
services:
  swagger_ui:
    build:
      context: docker/swagger-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./gen/service1/openapi/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  openapi-generator:
    build:
      context: docker/openapi-generator
      dockerfile: Dockerfile
    volumes:
      - ./openapi:/openapi # input
      - ./gen:/gen         # output
  redoc:
    image: redocly/redoc:latest
    ports:
      - "8081:80"
    volumes:
      - ./gen/service1/openapi:/usr/share/nginx/html/openapi/
    environment:
      SPEC_URL: openapi/openapi.yaml
  prism:
    image: stoplight/prism:latest
    ports:
      - "8082:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./gen/service1/openapi/openapi.yaml:/openapi.yaml
