version: "3.8"
services:
  swagger_ui:
    build:
      context: docker/swagger-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  openapi-generator:
    build:
      context: docker/openapi-generator
      dockerfile: Dockerfile
    volumes:
      - ./target:/usr/src/app/modules/openapi-generator-cli/target
