# main.yaml
openapi: 3.0.1
info:
  title: Service1 API
  version: 1.0.0
servers:
  - url: http://localhost:8082
paths:
  /users:
    $ref: './paths/users.yaml'
  /books:
    $ref: './paths/books.yaml'
components:
  schemas:
    User:
      $ref: './components/schemas/User.yaml'
    Book:
      $ref: './components/schemas/Book.yaml'
  responses:
    NotFound:
      $ref: './components/responses/NotFound.yaml'
  parameters:
    Sorting:
      $ref: './components/parameters/Sorting.yaml'
security:
  - SecurityScheme:
      $ref: './security/SecurityScheme.yaml'
